name: Deploy Infrastructure to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.4'
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
name: Deploy EC2 with Terraform and Ansible

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="region=eu-west-3" -var="ami_id=ami-015704b5de85636e1" -var="instance_type=t2.micro" -var="key_name=hounkydoki" -var="your_ip_cidr=0.0.0.0/0"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="region=eu-west-3" -var="ami_id=ami-015704b5de85636e1" -var="instance_type=t2.micro" -var="key_name=hounkydoki" -var="your_ip_cidr=0.0.0.0/0"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini nginx.yml
